# Generated by Django 4.2.10 on 2026-02-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
