# Generated by Django 4.2.10 on 2026-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_walkin',
            field=models.BooleanField(default=False, help_text='Walk-in customer without appointment'),
        ),
    ]
