# Generated by Django 4.2.11 on 2026-02-12 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('birth', 'Birth Certificate'), ('death', 'Death Certificate'), ('marriage', 'Marriage Certificate'), ('permit', 'Business Permit'), ('assessment', 'Assessment'), ('other', 'Other Services')], max_length=50)),
                ('estimated_time', models.IntegerField(help_text='Estimated service time in minutes')),
                ('max_daily_queue', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(max_length=20, unique=True)),
                ('priority_level', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Being Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('position_in_queue', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='queues.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queue',
                'ordering': ['priority_level', 'created_at'],
                'indexes': [models.Index(fields=['date', 'service'], name='queue_date_a03ce0_idx'), models.Index(fields=['status'], name='queue_status_cfc397_idx'), models.Index(fields=['user'], name='queue_user_id_046867_idx')],
            },
        ),
    ]
