# Generated by Django 4.2.11 on 2026-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_walkin',
            field=models.BooleanField(default=False, help_text='Walk-in customer without appointment'),
        ),
    ]
