# Generated by Django 4.2.11 on 2026-02-12 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('service_type', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('priority_level', models.IntegerField(default=3)),
                ('is_senior_citizen', models.BooleanField(default=False)),
                ('is_pwd', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_appointments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['-appointment_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='appointment_user_id_9286a3_idx'), models.Index(fields=['appointment_date'], name='appointment_appoint_b8d203_idx'), models.Index(fields=['status'], name='appointment_status_7a6b08_idx')],
            },
        ),
    ]
